name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.110'

    - name: Check directory structure (Debug)
      run: |
        echo "Listing files in the repo:"
        ls -R

    - name: Restore dependencies
      run: |
        # Debugging the directory structure
        ls -R
        cd ReviveIt/ReviveIT/WebUI
        dotnet restore

    - name: Build the project
      run: |
        cd ReviveIt/ReviveIT/WebUI
        dotnet build --configuration Release

    - name: Publish the project
      run: |
        cd ReviveIt/ReviveIT/WebUI
        dotnet publish --configuration Release --output ./publish

    - name: Deploy to remote server using SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        REMOTE_PATH: '/var/www/ReviveIt/ReviveIT/WebUI'
      run: |
        echo "$SSH_PRIVATE_KEY" | ssh-add -
        scp -r ReviveIt/ReviveIT/WebUI/publish/* $USER@$HOST:$REMOTE_PATH
        ssh -o StrictHostKeyChecking=no $USER@$HOST 'sudo systemctl restart reviveit.service'

    - name: Verify deployment
      run: |
        curl -f http://$HOST

