name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | ssh-add -
        ssh -o StrictHostKeyChecking=no $USER@$HOST '
          cd /var/www/ReviveIt &&
          git pull origin main &&
          cd ReviveIT &&
          dotnet restore &&
          dotnet publish -c Release -o ./publish &&
          sudo systemctl restart reviveit.service
        '
