name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.REVIVEIT_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to Server
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        ssh -v \
            -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            $USER@$HOST '
          set -e
          cd /var/www/ReviveIt &&
          git fetch --all &&
          git reset --hard origin/main &&
          git checkout HEAD~1 -- ReviveIT/WebUI/appsettings.json &&
          find . -type f -name "*.js" -exec sed -i "s|http://localhost|https://reviveit.devops99.pro|g" {} \; &&
          cd ReviveIT &&
          dotnet restore &&
          dotnet publish -c Release -o ./publish &&
          sudo systemctl restart reviveit.service
        '
