name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.REVIVEIT_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/reviveit_id_rsa
        chmod 600 ~/.ssh/reviveit_id_rsa
    
    - name: Deploy to Server
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        ssh -i ~/.ssh/reviveit_id_rsa \
            -o StrictHostKeyChecking=no \
            $USER@$HOST '
          set -e
          cd /var/www/ReviveIt &&
          git fetch --all &&
          git reset --hard origin/main &&
          cd ReviveIT &&
          dotnet restore &&
          dotnet publish -c Release -o ./publish &&
          sudo systemctl restart reviveit.service
        '
